name: sapp-env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - numpy>=1.20
  - pandas>=1.3
  - biopython>=1.79
  - tqdm>=4.60
  - pip
  - pip:
    - torch>=2.0.1
    - torchvision
    - torchaudio