name: sapp-env
channels:
  - salilab         
  - pytorch         
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.20,<2.0
  - pandas>=1.3
  - biopython>=1.79
  - tqdm>=4.60
  - dssp
  - pip
  - pytorch>=2.0.1
  - torchvision
  - torchaudio
